inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - config/initializers/forbidden_yaml.rb
    - !ruby/regexp /(vendor|bundle|bin|db)\/.*/
  DisplayCopNames: true
  DisplayStyleGuide: true
  Rails:
    Enabled: true

Metrics/AbcSize:
  Max: 15

Metrics/ClassLength:
  Max: 100
  Exclude:
    - spec/**/*.rb

Metrics/CyclomaticComplexity:
  Max: 6

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 15

Metrics/PerceivedComplexity:
  Max: 10 # TODO: Lower to 7

Style/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Style/ClassAndModuleChildren:
  EnforcedStyle: nested

Style/Documentation:
  Enabled: false

Style/MultilineOperationIndentation:
  EnforcedStyle: indented
