inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - config/initializers/forbidden_yaml.rb
    - !ruby/regexp /(vendor|bundle|bin|db)\/.*/
    - spec/support/warden.rb
    - frontend/**/*
  DisplayCopNames: true
  DisplayStyleGuide: true
  TargetRubyVersion: 2.3

Rails:
  Enabled: true

Rails/HttpPositionalArguments:
  Enabled: false

Metrics/AbcSize:
  Max: 20

Metrics/ClassLength:
  Max: 100
  Exclude:
    - spec/**/*.rb

Metrics/CyclomaticComplexity:
  Max: 6

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 20

Metrics/PerceivedComplexity:
  Max: 10

Style/AlignHash:
  Enabled: false

Style/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

Style/Documentation:
  Enabled: false

Style/MultilineOperationIndentation:
  EnforcedStyle: indented

Style/FrozenStringLiteralComment:
  Enabled: false
