language: ruby

cache:
  bundler: true

sudo: false

bundler_args: --jobs=3 --retry=3 --without development

rvm:
  - '2.3.0'

before_script:
  - bundle exec rake db:create db:migrate

script: bundle exec rspec spec
