language: ruby

addons:
  postgresql: '9.4'

cache:
  bundler: true
  directories:
    - frontend/node_modules

sudo: false

bundler_args: --jobs=3 --retry=3 --without development

rvm:
  - '2.3.1'

install:
  - nvm install 5.10.1
  - (cd frontend && npm i)

before_script:
  - bundle install --jobs=3 --retry=3 --without development --path=${BUNDLE_PATH:-vendor/bundle}
  - bundle exec rake db:create db:migrate

script:
  - bundle exec rspec spec
  - (cd frontend && npm test)
