
default: public

roles:

  public:
    name: Public
    description: Public visitors

  user:
    name: User
    description: Trivial users

  admin:
    name: Administrator
    description: The ones that rule the all
